---

- name: Install lighttpd
  pacman: name=lighttpd state=present

- name: lighttpd configuration
  template:
    dest: /etc/lighttpd/lighttpd.conf
    src: lighttpd.conf.j2

- name: enable and start lighttpd service
  systemd:
    name: lighttpd
    state: restarted
    enabled: yes

- name: open tcp firewall holes
  ufw:
    rule: allow
    port: "{{ lighttpd_port}}"
    proto: tcp
  tags:
    - firewall
