---

- name: Include packages vars
  include_vars:
    file: packages.yml

- name: Install dev packages
  package:
    name: "{{ packages.dev }}"
    state: present

- name: Install shell packages
  package:
    name: "{{ packages.shell }}"
    state: present

- name: install pacman config
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf
    mode: 0644
    owner: root
    group: root

- name: Install group packages
  package:
    name: "{{ install_group_packages.official }}"
    state: present

- name: Install host packages
  package:
    name: "{{ install_host_packages.official }}"
    state: present
