---

- name: setup torns
  hosts: torns.lsferreira.net
  roles:
    - { role: raid, tags: ['raid'] }
    - { role: samba, tags: ['samba'] }
    - { role: syncrepo, tags: ['syncrepo'] }
    - { role: lighttpd, tags: ['lighttpd'] }
    - { role: named, tags: ['named'] }
